# https://taskfile.dev

version: '3'

tasks:
  migrate:
    aliases:
      - mig
    desc: "migrations for database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
